namespace EnterpriseAIPlatform.Domain.Personas;

/// <summary>
/// A persona (spec 009 Key Entities). Azure SQL / EF Core entity (research.md D1) — ownership
/// transfer is a single-row <c>OwnerUserId</c>/<c>OwnerPartitionKey</c> update, never a
/// delete-then-recreate; <see cref="Id"/> never changes across a transfer.
/// </summary>
public sealed class PersonaModel
{
    public required string Id { get; set; }

    /// <summary>Current owner's raw identity (email), for display/audit only — never used for access decisions.</summary>
    public required string OwnerUserId { get; set; }

    /// <summary><c>IIdentityHasher.ForEmail(OwnerUserId)</c> (research.md D2) — what <c>PersonaAccessEvaluator</c> compares the caller's hashed identity against.</summary>
    public required string OwnerPartitionKey { get; set; }

    /// <summary>Canonical <c>provider:modelId</c> (spec 014) this persona invokes.</summary>
    public required string Model { get; set; }

    public required string Name { get; set; }

    public string? Description { get; set; }

    public string PersonaMessage { get; set; } = string.Empty;

    /// <summary>Open-ended extension tokens (e.g. <c>"DataProduct"</c>).</summary>
    public List<string> Extensions { get; set; } = new();

    /// <summary>Required non-empty when <see cref="Extensions"/> contains <c>"DataProduct"</c> — enforced by <c>PersonaExtensionRules</c> (FR-011), not a DB constraint.</summary>
    public List<string> DataProducts { get; set; } = new();

    /// <summary>Hashed collaborator identities (research.md D2) — full edit access per FR-003.</summary>
    public List<string> CollaboratorPartitionKeys { get; set; } = new();

    /// <summary>Read-only share targets — FR-008's own binary rule, kept separate from <see cref="CollaboratorPartitionKeys"/> (research.md D8).</summary>
    public List<PersonaShareTarget> SharedWith { get; set; } = new();

    /// <summary>The A2A credential (spec 011). Server-only — never present on <see cref="PersonaPublicDTO"/> (FR-009/FR-010).</summary>
    public string? ApiKey { get; set; }

    /// <summary>Whether this persona is A2A-invocable (spec 011 owns invocation mechanics).</summary>
    public bool A2aEnabled { get; set; }

    /// <summary>
    /// Admin-managed. Drives student read-only access (FR-003) and non-admin listing exclusion
    /// (FR-007). A non-admin's submitted value on update is discarded server-side (FR-006).
    /// </summary>
    public bool IsLessonPersona { get; set; }

    /// <summary>
    /// Self-managed optimistic-concurrency token (research.md D7) — regenerated by
    /// <c>PersonaService</c> on every successful write, rather than relying on a database-native
    /// auto-generated rowversion column (which not every EF Core provider, e.g. InMemory used in
    /// tests, emulates identically). A write whose expected value no longer matches (e.g. a
    /// concurrent transfer already committed) throws
    /// <see cref="Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException"/> — this is what
    /// implements FR-013's "in-flight transfer" rejection, with no separate boolean flag.
    /// </summary>
    public Guid RowVersion { get; set; } = Guid.NewGuid();

    public DateTimeOffset CreatedAtUtc { get; set; }

    public DateTimeOffset UpdatedAtUtc { get; set; }
}
