// <auto-generated />
using System;
using EnterpriseAIPlatform.Infrastructure.ModelAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseAIPlatform.Infrastructure.ModelAccess.Migrations
{
    [DbContext(typeof(ModelAccessDbContext))]
    [Migration("20260728210909_InitialModelAccessSchema")]
    partial class InitialModelAccessSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnterpriseAIPlatform.Domain.ModelAccess.MessageLimitConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DailyMessageCap")
                        .HasColumnType("int");

                    b.Property<int?>("PerMessageCharacterCap")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MessageLimitConfigs");
                });

            modelBuilder.Entity("EnterpriseAIPlatform.Domain.ModelAccess.ModelAliasDocument", b =>
                {
                    b.Property<string>("RetiredModelId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReplacementModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RetiredModelId");

                    b.ToTable("ModelAliases");
                });

            modelBuilder.Entity("EnterpriseAIPlatform.Domain.ModelAccess.ModelConfigDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessTier")
                        .HasColumnType("int");

                    b.Property<int>("ContextWindowSize")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal>("PricingInputPerMillionTokens")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PricingOutputPerMillionTokens")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresAdvancedModelAccess")
                        .HasColumnType("bit");

                    b.Property<bool?>("SupportsReasoning")
                        .HasColumnType("bit");

                    b.Property<bool?>("SupportsToolCalling")
                        .HasColumnType("bit");

                    b.Property<bool?>("SupportsVision")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("ModelConfigs");

                    b.HasData(
                        new
                        {
                            Id = "azure-foundry:gpt-5",
                            AccessTier = 0,
                            ContextWindowSize = 272000,
                            DisplayName = "GPT-5 (Azure Foundry)",
                            IsDeleted = false,
                            IsEnabled = true,
                            PricingInputPerMillionTokens = 0m,
                            PricingOutputPerMillionTokens = 0m,
                            Provider = "azure-foundry",
                            RequiresAdvancedModelAccess = false,
                            SupportsReasoning = true,
                            SupportsToolCalling = true,
                            SupportsVision = true
                        });
                });

            modelBuilder.Entity("EnterpriseAIPlatform.Domain.ModelAccess.PersonaGenerationModelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedModelIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonaGenerationModelConfigs");
                });

            modelBuilder.Entity("EnterpriseAIPlatform.Domain.ModelAccess.SystemModelConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArtifactModelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingModelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FallbackModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageModelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleModelAccess")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemModelConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
