// <auto-generated />
using System;
using EnterpriseAIPlatform.Infrastructure.Prompts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnterpriseAIPlatform.Infrastructure.Prompts.Migrations
{
    [DbContext(typeof(PromptDbContext))]
    [Migration("20260831210752_InitialPromptSchema")]
    partial class InitialPromptSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnterpriseAIPlatform.Domain.Prompts.PromptFavorite", b =>
                {
                    b.Property<string>("UserPartitionKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PromptId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("FavoritedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("UserPartitionKey", "PromptId");

                    b.HasIndex("PromptId");

                    b.ToTable("PromptFavorites");
                });

            modelBuilder.Entity("EnterpriseAIPlatform.Domain.Prompts.PromptModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CollaboratorPartitionKeys")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerPartitionKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OwnerUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SharedWith")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("OwnerPartitionKey");

                    b.ToTable("Prompts");
                });

            modelBuilder.Entity("EnterpriseAIPlatform.Domain.Prompts.PromptFavorite", b =>
                {
                    b.HasOne("EnterpriseAIPlatform.Domain.Prompts.PromptModel", null)
                        .WithMany()
                        .HasForeignKey("PromptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
