namespace EnterpriseAIPlatform.Domain.Prompts;

/// <summary>
/// A reusable prompt template (spec 016 Key Entities). Azure SQL / EF Core entity (research.md D1)
/// — ownership transfer is a single-row <c>OwnerUserId</c>/<c>OwnerPartitionKey</c> update, never a
/// delete-then-recreate; <see cref="Id"/> never changes across a transfer (FR-008).
/// </summary>
public sealed class PromptModel
{
    public required string Id { get; set; }

    /// <summary>Current owner's raw identity (email), for display/audit only — never used for access decisions.</summary>
    public required string OwnerUserId { get; set; }

    /// <summary><c>IIdentityHasher.ForEmail(OwnerUserId)</c> — what <c>PromptAccessEvaluator</c> compares the caller's hashed identity against.</summary>
    public required string OwnerPartitionKey { get; set; }

    /// <summary>The prompt's title. Required non-empty by <c>PromptValidationRules</c> (FR-003).</summary>
    public required string Name { get; set; }

    /// <summary>
    /// The reusable prompt text itself — there is deliberately no separate <c>content</c>/
    /// <c>template</c> field, and no placeholder/variable engine exists on this entity. This is what
    /// FR-012 copies verbatim into the chat composer. Required non-empty (FR-003).
    /// </summary>
    public required string Description { get; set; }

    /// <summary>Hashed collaborator identities — full write access per FR-001.</summary>
    public List<string> CollaboratorPartitionKeys { get; set; } = new();

    /// <summary>Read-only share grants (FR-002). Validated on every write via spec 018's <c>ISharingPolicyService</c> (FR-004).</summary>
    public List<PromptShareTarget> SharedWith { get; set; } = new();

    /// <summary>
    /// Legacy flag from the source accelerator, superseded by <see cref="SharedWith"/>. Retained for
    /// migration fidelity only — deliberately NOT consulted by any access decision.
    /// </summary>
    public bool IsPublished { get; set; }

    /// <summary>
    /// Self-managed optimistic-concurrency token (research.md D10) — regenerated by
    /// <c>PromptService</c> on every successful write, rather than relying on a database-native
    /// auto-generated rowversion column (which not every EF Core provider, e.g. the InMemory
    /// provider used in tests, emulates identically). A write whose expected value no longer matches
    /// throws <see cref="Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException"/> — this is what
    /// implements FR-007's double-submit rejection, with no separate in-flight flag.
    /// </summary>
    public Guid RowVersion { get; set; } = Guid.NewGuid();

    /// <summary>Set once on create. Server-derived — a transfer request can never influence it (FR-005).</summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    public DateTimeOffset UpdatedAtUtc { get; set; }
}
